version: "3.0"

services:
  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT:-27018}:27017
    volumes:
      - ./statify-data-staging:/data/db:rw
    logging:
      driver: "none"

  backend:
    build: backend
    command: /start
    ports:
      - ${BACKEND_PORT:-3001}:3000
    depends_on: 
      - mongo
    environment:
      - DB_URL=mongodb://mongo:${MONGO_PORT:-27018}/statify-staging

  frontend:
    build: frontend
    command: /start
    ports:
      - ${FRONTEND_PORT:-5001}:5000
    depends_on:
      - backend