version: "3.0"

services:
  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - ${DATA_DIR:-./statify-data}:/data/db:rw
    logging:
      driver: "none"

  backend:
    build: backend
    command: /start
    ports:
      - ${BACKEND_PORT:-3000}:3000
    depends_on: 
      - mongo
    environment:
      - DB_URL=mongodb://mongo:${MONGO_PORT:-27017}/statify

  frontend:
    build: frontend
    command: /start
    volumes:
      - ${PWD}/.env.frontend:/statify/frontend/.env
    ports:
      - ${FRONTEND_PORT:-5000}:5000
    depends_on:
      - backend